### ISSUE TITLE
Add Julia script generation to Engine

### ISSUE THREAD

**Issue by giannamars** [danebjork/AutomatedMBAM#5]
Hi Dane,

I added Julia script generation to the Engine.run() method ([engine.txt](https://github.com/danebjork/AutomatedMBAM/files/2584981/engine.txt), Line 45), but the generated .jl file for the MM_4 model ([MM_4.txt](https://github.com/danebjork/AutomatedMBAM/files/2584975/MM_4.txt)) is parsed differently from the one generated by the "Save Model" button from the UI ([MM4_ui.txt](https://github.com/danebjork/AutomatedMBAM/files/2584976/MM4_ui.txt)) with the default options (in functions "ic", and "res" versus "rhs"). Can you clarify the meaning of the options structure? How do I get the same results?

Also sympy.printing.julia seems to have an issue with element-wise operations on arrays ([error_from_parsing.txt](https://github.com/danebjork/AutomatedMBAM/files/2584967/error_from_parsing.txt)). E.g. [1,2,3].^2./[1,2,3] should be parsed as ([1,2,3].^2)./[1,2,3]. Do you have an idea how to fix this?

Gianna

**Comment by danebjork** [comment]
Hey Gianna,

The difference in models comes from the conversion between and ODE and a DAE. The engine has a much easier time manipulating DAE's, so ODE models are automatically transformed into DAE's. The generation line that you added must be printing out the model prior to this transformation. While the model files are different, the two models should be equivalent. Does that make sense?

I haven't seen the sympy.printing.julia error before. It looks like they sympy printing function may not be up to date with the Julia version you're using. You can either make the changes in the Sympy repo and submit a merge request, or you could just add in some extra logic on here to fix the spacing issue.

Does this help?

**Comment by mktranstrum** [comment]
I have seen the julia printing error.  sympy.printing.julia has not been updated for julia 1.0 syntax.

**Comment by giannamars** [comment]
Thanks, I missed the conversion to a DAE. 
Will have a look at sympy.printing.julia

**Comment by giannamars** [comment]
Thanks, the examples are running now. 
There were too many issues with the sympy development version, so I changed things manually:

* added Julia 1.0 dot syntax for vectorizing functions {.*, ./, .^} - mbam.parsing.base.BaseParser.find_replace_vectorized()
* changed function signature of mbam.parsing.dae.DAEParser.write_res()
* changed mbam.parsing.dae.DAEParser.write_ic_subs() such that initial conditions for variables in auxiliary functions (e.g. in the MM_4 model example: x_1_inact = -_x[1] + ps.x_1_total -> x_1_inact = -ps.x_1_init + ps.x_1_total) are also substituted
* added Julia script generation to mbam.engine.Engine.run()

and sent a pull request.
